{{- if .Values.customerService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-customer
  labels:
    {{- include "app.labels" . | nindent 4 }}-customer
spec:
  type: {{ .Values.customerService.service.type }}
  ports:
    - port: {{ .Values.customerService.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}-customer
{{- end }}
