{{- if .Values.paymentService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-payment
  labels:
    {{- include "app.labels" . | nindent 4 }}-payment
spec:
  type: {{ .Values.customerService.service.type }}
  ports:
    - port: {{ .Values.customerService.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}-payment

{{- end }}
