apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  dbHost: {{ include "app.postgresHostName" . | b64enc }}
  dbUsername: {{ "postgres" | b64enc }}
  dbPassword: {{ "postgres" | b64enc }}
  keycloakAdminUser: {{.Values.keycloak.auth.adminUser | b64enc }}
  keycloakAdminPassword: {{.Values.keycloak.auth.adminPassword | b64enc }}
  keycloakCustomerRealm: {{.Values.keycloak.customerRealm | b64enc }}
  keycloakCustomerClientId: {{.Values.keycloak.customerClientId | b64enc }}
  keycloakCustomerClientSecret: {{.Values.keycloak.customerClientSecret | b64enc }}
  keycloakCompanyRealm: {{.Values.keycloak.companyRealm | b64enc }}
  keycloakCompanyClientId: {{.Values.keycloak.companyClientId | b64enc }}
  keycloakCompanyClientSecret: {{.Values.keycloak.companyClientSecret | b64enc }}


