apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.global.postgresql.auth.existingSecret }}
type: Opaque
data:
  dbHost: {{ include "app.postgresHostName" . | b64enc }}
  dbUsername: {{ .Values.postgresql.global.postgresql.auth.username | b64enc }}
  dbPassword: {{ .Values.postgresql.global.postgresql.auth.password | b64enc }}
  db: {{ .Values.postgresql.global.postgresql.auth.database | b64enc }}
