apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  dbHost: {{ include "app.postgresHostName" . | b64enc }}
  dbUsername: {{ "postgres" | b64enc }}
  dbPassword: {{ "postgres" | b64enc }}
