# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: bopoh24/simple_server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

appConfig:
  name: Simple Server
  logLevel: debug

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: arch.homework
      paths:
        - path: /user
          pathType: Prefix

pv:
  enabled: true
  name: postgres-pv
  size: 1Gi
  storageClass: standard
  path: /data/pv0001
  accessModes:
    - ReadWriteOnce

autoscaling: {}

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: postgres
        username: postgres
        password: postgres
        database: postgres
  primary:
    persistence:
      existingClaim: postgres-pvc
  volumePermissions:
    enabled: true

