apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-postgres-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv0002"
