{
 "title": "HW_4",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "simple-server-app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(user_http_requests_total{status!=\"500\"}[1m])) by (method,url)",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\nsum(rate(user_http_request_duration_seconds_bucket{status!=\"500\"}[1m])) by (le,method, url)\n)\n",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "HTTP 500 Errors/Minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(user_http_requests_total{status=\"500\"}[1m])) by (method, url)",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "POD CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"simple-server-app.+\"}[1m]) *  100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "POD Memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{pod=~\"simple-server-app-.+\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "nginx-ingress-controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_requests_total[1m])) by (service)",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 500 Errors/Minute",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=\"500\"}[1m])) by (status)",
     "legendFormat": "HTTP Status 500"
    }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{pod=\"simple-server-postgresql-0\", datname=\"postgres\"}",
     "legendFormat": "DB Size"
    }
   ]
  },
  {
   "title": "Deadlocks/Conflicts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{pod=\"simple-server-postgresql-0\", datname=\"postgres\"}[1m])",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "rate(pg_stat_database_conflicts{pod=\"simple-server-postgresql-0\", datname=\"postgres\"}[1m])",
     "legendFormat": "Conflicts"
    }
   ]
  },
  {
   "title": "Number of Active connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_numbackends{pod=\"simple-server-postgresql-0\", datname=\"postgres\"}[1m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}