version: '3.1'

services:

  app:
    container_name: app
    image: bopoh24/simple_server
    restart: always
    ports:
      - "8000:8000"


  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres


