POST http://localhost/user
Content-Type: application/json

{
  "username": "username1",
  "firstName": "John",
  "lastName": "Doe",
  "email": "bestjohn@doe.com",
  "phone": "+71002003040"
}

###
GET http://localhost/user/1


###
PUT http://localhost/user/1
Content-Type: application/json

{
  "username": "username2",
  "firstName": "John",
  "lastName": "Doe",
  "email": "dd23123d@ddd.com",
  "phone": "+71002003040"
}


###
DELETE http://localhost/user/1
