apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-migrate
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate-container
          image: bopoh24/simple_server_migrate:latest
          env:
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-postgresql
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}
                  key: db
            - name: POSTRGES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}
                  key: dbUsername
            - name: POSTRGES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}
                  key: dbPassword
          command: ["migrate", "-path", "/migrations", "-database", "postgresql://$(POSTRGES_USER):$(POSTRGES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)?sslmode=disable", "up"]

