{
 "title": "Services",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Customer RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(customer_http_requests_total{status!=\"500\"}[1m])) by (method,url)",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Company RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(company_http_requests_total{status!=\"500\"}[1m])) by (method,url)",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Booking RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(booking_http_requests_total{status!=\"500\"}[1m])) by (method,url)",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Payment RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(payment_http_requests_total{status!=\"500\"}[1m])) by (method,url)",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Customer Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(customer_http_request_duration_seconds_bucket{status!=\"500\"}[1m])) by (le,method, url))",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Company Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(company_http_request_duration_seconds_bucket{status!=\"500\"}[1m])) by (le,method, url))",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Booking Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(booking_http_request_duration_seconds_bucket{status!=\"500\"}[1m])) by (le,method, url))",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Payment Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(payment_http_request_duration_seconds_bucket{status!=\"500\"}[1m])) by (le,method, url))",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  }
 ]
}