apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: app
  labels:
    app: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-app
    spec:
      containers:
        - name: my-app
          image: bopoh24/simple_server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-app-configmap
                  key: app_name

            - name: APP_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: my-app-configmap
                  key: app_log_level

            - name: POSTGRES_HOST
              value: postgresql

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: db

            - name: POSTRGES_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: db-username

            - name: POSTRGES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: db-password

