apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: app
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv0001"
