ingress:
  enabled: true
  className: nginx
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: ImplementationSpecific

krakend:
  config: |
    {
      "$schema": "https://www.krakend.io/schema/krakend.json",
      "version": 3,
      "name": "KrakenD - API Gateway",
      "extra_config": {
        "security/cors": {
          "allow_origins": [
            "*"
          ],
          "expose_headers": [
            "Content-Length"
          ],
          "max_age": "12h",
          "allow_methods": [
            "GET",
            "HEAD",
            "POST",
            "PUT",
            "DELETE",
            "CONNECT",
            "OPTIONS",
            "TRACE",
            "PATCH"
          ]
        }
      },
      "timeout": "3000ms",
      "cache_ttl": "300s",
      "output_encoding": "json",
      "debug_endpoint": true,
      "echo_endpoint": true,
      "endpoints": [
        {
          "endpoint": "/v1/users/me",
          "method": "GET",
          "output_encoding": "json",
          "input_headers": ["*"],
          "backend": [
            {
              "url_pattern": "/user/me",
              "encoding": "json",
              "sd": "static",
              "method": "GET",
              "host": [
                "http://simple-server-app.app.svc.cluster.local"
              ],
              "disable_host_sanitize": false
            }
          ],
          "extra_config": {
            "auth/validator": {
              "alg": "RS256",
              "jwk_url": "http://auth-server-keycloak.auth.svc.cluster.local/realms/app/protocol/openid-connect/certs",
              "cache": true,
              "disable_jwk_security": true,
              "operation_debug": true,
              "propagate_claims": [
                [ "sub", "x-user" ],
                [ "email", "x-email" ],
                [ "given_name", "x-given-name" ],
                [ "family_name", "x-family-name" ],
                [ "preferred_username", "x-preferred-username" ]
              ]
            }
          }
        },
        {
          "endpoint": "/v1/users/me",
          "method": "PUT",
          "output_encoding": "json",
          "input_headers": ["*"],
          "backend": [
            {
              "url_pattern": "/user/me",
              "encoding": "json",
              "sd": "static",
              "method": "PUT",
              "host": [
                "http://simple-server-app.app.svc.cluster.local"
              ],
              "extra_config": {
                "backend/http": {
                  "return_error_code": true
                }
              },
              "disable_host_sanitize": false
            }
          ],
          "extra_config": {
            "auth/validator": {
              "alg": "RS256",
              "jwk_url": "http://auth-server-keycloak.auth.svc.cluster.local/realms/app/protocol/openid-connect/certs",
              "cache": true,
              "disable_jwk_security": true,
              "operation_debug": true,
              "propagate_claims": [
                [ "sub", "x-user" ],
                [ "email", "x-email" ],
                [ "given_name", "x-given-name" ],
                [ "family_name", "x-family-name" ],
                [ "preferred_username", "x-preferred-username" ]
              ]
            }
          }
        },
        {
          "endpoint": "/v1/login",
          "method": "POST",
          "output_encoding": "json",
          "backend": [
            {
              "url_pattern": "/auth/login",
              "encoding": "json",
              "sd": "static",
              "method": "POST",
              "host": [
                "http://simple-server-app.app.svc.cluster.local"
              ],
              "extra_config": {
                "backend/http": {
                  "return_error_code": true
                }
              },
              "disable_host_sanitize": false
            }
          ]
        },
        {
          "endpoint": "/v1/logout",
          "method": "POST",
          "output_encoding": "json",
          "backend": [
            {
              "url_pattern": "/auth/logout",
              "encoding": "json",
              "sd": "static",
              "method": "POST",
              "host": [
                "http://simple-server-app.app.svc.cluster.local"
              ],
              "extra_config": {
                "backend/http": {
                  "return_error_code": true
                }
              },
              "disable_host_sanitize": false
            }
          ]
        },
        {
          "endpoint": "/v1/register",
          "method": "POST",
          "output_encoding": "json",
          "backend": [
            {
              "url_pattern": "/auth/register",
              "encoding": "json",
              "sd": "static",
              "method": "POST",
              "host": [
                "http://simple-server-app.app.svc.cluster.local"
              ],
              "extra_config": {
                "backend/http": {
                  "return_error_code": true
                }
              },
              "disable_host_sanitize": false
            }
          ]
        },
        {
          "endpoint": "/v1/token",
          "method": "POST",
          "output_encoding": "json",
          "backend": [
            {
              "url_pattern": "/auth/refresh",
              "encoding": "json",
              "sd": "static",
              "method": "POST",
              "host": [
                "http://simple-server-app.app.svc.cluster.local"
              ],
              "extra_config": {
                "backend/http": {
                  "return_error_code": true
                }
              },
              "disable_host_sanitize": false
            }
          ]
        },
        {
          "endpoint": "/v1/order",
          "method": "POST",
          "output_encoding": "json",
          "input_headers": ["*"],
          "backend": [
            {
              "url_pattern": "/order",
              "encoding": "json",
              "sd": "static",
              "method": "POST",
              "host": [
                "http://simple-server-app.app.svc.cluster.local"
              ],
              "extra_config": {
                "backend/http": {
                  "return_error_code": true
                }
              },
              "disable_host_sanitize": false
            }
          ]
        },
        {
          "endpoint": "/v1/order/{id}",
          "method": "GET",
          "output_encoding": "json",
          "input_headers": ["*"],
          "backend": [
            {
              "url_pattern": "/order/{id}",
              "encoding": "json",
              "sd": "static",
              "method": "GET",
              "host": [
                "http://simple-server-app.app.svc.cluster.local"
              ],
              "extra_config": {
                "backend/http": {
                  "return_error_code": true
                }
              },
              "disable_host_sanitize": false
            }
          ]
        },
        {
          "endpoint": "/v1/order/{id}",
          "method": "DELETE",
          "output_encoding": "json",
          "input_headers": ["*"],
          "backend": [
            {
              "url_pattern": "/order/{id}",
              "encoding": "json",
              "sd": "static",
              "method": "DELETE",
              "host": [
                "http://simple-server-app.app.svc.cluster.local"
              ],
              "extra_config": {
                "backend/http": {
                  "return_error_code": true
                }
              },
              "disable_host_sanitize": false
            }
          ]
        }
      ]
    }

