apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
data:
  app-name: "{{ .Values.appConfig.name }}"
  app-log-level: "{{ .Values.appConfig.logLevel }}"
  app-version: "{{ .Chart.AppVersion }}"
