apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql.primary.persistence.existingClaim }}
spec:
  storageClassName: {{ .Values.pv.storageClass }}
  accessModes:
    {{- range .Values.pv.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.pv.size }}
