apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
type: Opaque
data:
  db: {{ .Values.postgresql.global.postgresql.auth.database | b64enc }}
  dbUsername: {{ .Values.postgresql.global.postgresql.auth.username | b64enc }}
  dbPassword: {{ .Values.postgresql.global.postgresql.auth.password | b64enc }}
